import "@radix-ui/themes/styles.css"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";

import "../styles/globals.css";
import '../styles/theme-config.css'
import NavBar from "../components/home/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme accentColor="violet" radius="large">
          <NavBar />
          <main className="p-4">{children}</main>
        </Theme>
        </body>
    </html>
  );
}
